export const CONFIG_REQUEST = 'CONFIG_REQUEST'
export const CONFIG_RESPONSE = 'CONFIG_RESPONSE'
export const CONFIG_ERROR = 'CONFIG_ERROR'

export const USER_INFO_REQUEST = 'USER_INFO_REQUEST'
export const USER_INFO_RESPONSE = 'USER_INFO_RESPONSE'
export const USER_INFO_ERROR = 'USER_INFO_ERROR'

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_RESPONSE = 'USER_LOGIN_RESPONSE'
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_RESPONSE = 'USER_REGISTER_RESPONSE'
export const USER_REGISTER_ERROR = 'USER_REGISTER_ERROR'

export const SOCKET_CONNECTED = 'SOCKET_CONNECT'
export const SOCKET_DISCONNECTED = 'SOCKET_DISCONNECT'

export const NAVIGATE = 'NAVIGATE'
