export const CONFIG_REQUEST = 'CONFIG_REQUEST'
export const CONFIG_RESPONSE = 'CONFIG_RESPONSE'
export const CONFIG_ERROR = 'CONFIG_ERROR'

export const USER_INFO_REQUEST = 'USER_INFO_REQUEST'
export const USER_INFO_RESPONSE = 'USER_INFO_RESPONSE'
export const USER_INFO_ERROR = 'USER_INFO_ERROR'
