export const CONFIG_REQUEST = 'CONFIG_REQUEST'
export const CONFIG_RESPONSE = 'CONFIG_RESPONSE'
export const CONFIG_ERROR = 'CONFIG_ERROR'

export const USER_INFO_REQUEST = 'USER_INFO_REQUEST'
export const USER_INFO_RESPONSE = 'USER_INFO_RESPONSE'
export const USER_INFO_ERROR = 'USER_INFO_ERROR'

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_RESPONSE = 'USER_LOGIN_RESPONSE'
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_RESPONSE = 'USER_REGISTER_RESPONSE'
export const USER_REGISTER_ERROR = 'USER_REGISTER_ERROR'

export const SOCKET_CONNECTED = 'SOCKET_CONNECT'
export const SOCKET_DISCONNECTED = 'SOCKET_DISCONNECT'

export const GAMES_RECEIVE = 'GAMES_RECEIVE'
export const GAMES_NEW_CREATE = 'GAMES_NEW_CREATE'
export const GAMES_NEW_SUCCESS = 'GAMES_NEW_SUCCESS'
export const GAMES_NEW_ERROR = 'GAMES_NEW_ERROR'

export const GAMES_JOIN = 'GAMES_JOIN'
export const GAMES_JOIN_SUCCESS = 'GAMES_JOIN_SUCCESS'
export const GAMES_JOIN_ERROR = 'GAMES_JOIN_ERROR'

export const LOBBY_GET = 'LOBBY_GET'
export const LOBBY_RECEIVE = 'LOBBY_RECEIVE'

export const STATE_GET = 'STATE_GET'
export const STATE_RECEIVE = 'STATE_GET_SUCCESS'

export const NAVIGATE = 'NAVIGATE'
