export const LOADING_ROUTE: string = 'loading'
export const LOGIN_ROUTE: string = 'login'
export const REGISTER_ROUTE: string = 'register'
export const GAMES_ROUTE: string = 'games'
export const LOBBY_ROUTE: string = 'lobby'
export const ERROR_ROUTE: string = 'error'
export const HOME_ROUTE: string = 'home'
