export const LOADING_ROUTE = 'loading'
export const BASE_ROUTE = 'base'
export const LOGIN_ROUTE = 'login'
export const REGISTER_ROUTE = 'register'
export const GAMES_ROUTE = 'games'
export const LOBBY_ROUTE = 'lobby'
