UserInfo:
    properties:
        name:
            type: string
            required: false
        isAuthenticated:
            type: boolean
            required: true

OperationResult:
    properties:
        success:
            type: boolean
            required: true
        reason:
            type: string
            required: false
