#%RAML 1.0
title: Energynet API
version: v1
protocols:
  - HTTP
  - HTTPS

types: !include types/api.raml

/auth:
    description: Authentication api

    /user_info:
        description: Get user authentication information
        get:
            responses:
                200:
                    body:
                        application/json:
                            type: UserInfo
                            example: !include examples/user_info.json
                            examples:
                                notAuthorized: {
                                    "isAuthenticated": false
                                }

    /login:
        description: Log in entry for user
        post:
            responses:
                200:
                    body:
                        application/json:
                            type: OperationResult
